import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { useWallet } from '../wallet';
import { createMatch, joinMatch, getMatch, registerDeposit, type MatchInfo } from '../api/client';
import { TxLifecycleTimeline } from '@kas-racing/speed-visualizer-sdk';

type View = 'lobby' | 'create' | 'join' | 'waiting' | 'deposits' | 'game' | 'finished';

const BET_AMOUNTS = [0.1, 0.5, 1.0, 5.0];

export function DuelLobby() {
  const { address, isConnected, connect, sendTransaction, network } = useWallet();
  const [view, setView] = useState<View>('lobby');
  const [betAmount, setBetAmount] = useState(1.0);
  const [joinCode, setJoinCode] = useState('');
  const [match, setMatch] = useState<MatchInfo | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [depositLoading, setDepositLoading] = useState(false);
  const [myPlayer, setMyPlayer] = useState<'A' | 'B' | null>(null);

  // Poll match status when waiting for opponent, deposits, or game
  useEffect(() => {
    if (!match || (view !== 'waiting' && view !== 'deposits' && view !== 'game' && view !== 'finished')) return;

    const pollMatch = async () => {
      try {
        const updated = await getMatch(match.id);
        setMatch(updated);

        // Auto-transition views based on status
        if (updated.status === 'deposits_pending' && view === 'waiting') {
          setView('deposits');
        } else if (updated.status === 'ready' && view === 'deposits') {
          setView('game');
        } else if (updated.status === 'finished' && view === 'game') {
          setView('finished');
        }
      } catch (e) {
        console.error('Failed to poll match:', e);
      }
    };

    const interval = setInterval(() => {
      void pollMatch();
    }, 2000);

    return () => clearInterval(interval);
  }, [match, view]);

  const handleCreateMatch = useCallback(() => {
    if (!address) return;

    setLoading(true);
    setError(null);

    createMatch(address, betAmount)
      .then((result) => {
        setMatch({
          id: result.matchId,
          joinCode: result.joinCode,
          status: 'waiting',
          betAmount: result.betAmount,
          playerA: { address, depositTxid: null, depositStatus: null },
          playerB: null,
          escrowAddressA: null,
          escrowAddressB: null,
          winner: null,
          playerAScore: null,
          playerBScore: null,
          settleTxid: null,
          settleStatus: null,
          createdAt: Date.now(),
          startedAt: null,
          finishedAt: null,
        });
        setMyPlayer('A');
        setView('waiting');
      })
      .catch((e: unknown) => {
        setError(e instanceof Error ? e.message : 'Failed to create match');
      })
      .finally(() => {
        setLoading(false);
      });
  }, [address, betAmount]);

  const handleJoinMatch = useCallback(() => {
    if (!address || !joinCode) return;

    setLoading(true);
    setError(null);

    joinMatch(joinCode, address)
      .then((result) => {
        setMatch(result);
        setMyPlayer('B');
        setBetAmount(result.betAmount);
        setView('deposits');
      })
      .catch((e: unknown) => {
        setError(e instanceof Error ? e.message : 'Failed to join match');
      })
      .finally(() => {
        setLoading(false);
      });
  }, [address, joinCode]);

  const handleDeposit = useCallback(() => {
    if (!match || !myPlayer || !address) return;

    setDepositLoading(true);
    setError(null);

    const doDeposit = async () => {
      // For now, use a placeholder escrow address
      // In production, this would be generated by the server
      const escrowAddress = myPlayer === 'A'
        ? (match.escrowAddressA ?? 'kaspa:escrow_placeholder_a')
        : (match.escrowAddressB ?? 'kaspa:escrow_placeholder_b');

      // Send transaction via wallet
      const result = await sendTransaction(escrowAddress, match.betAmount);

      // Register deposit with server
      const updated = await registerDeposit(match.id, myPlayer, result.txid);
      setMatch(updated);

      if (updated.status === 'ready') {
        setView('game');
      }
    };

    doDeposit()
      .catch((e: unknown) => {
        setError(e instanceof Error ? e.message : 'Failed to deposit');
      })
      .finally(() => {
        setDepositLoading(false);
      });
  }, [match, myPlayer, address, sendTransaction]);

  const resetMatch = () => {
    setMatch(null);
    setView('lobby');
    setError(null);
  };

  const getMyDeposit = () => {
    if (!match || !myPlayer) return null;
    return myPlayer === 'A' ? match.playerA : match.playerB;
  };

  const getOpponentDeposit = () => {
    if (!match || !myPlayer) return null;
    return myPlayer === 'A' ? match.playerB : match.playerA;
  };

  const myDeposit = getMyDeposit();
  const opponentDeposit = getOpponentDeposit();

  // Render content based on view
  const renderMainContent = () => {
    switch (view) {
      case 'lobby':
        return (
          <div className="lobby-content">
            <h1>Ghost-Wheel Duel</h1>
            <p className="muted">1v1 Race - Deposit KAS, Winner Takes All</p>

            {!isConnected ? (
              <div style={{ marginTop: '24px' }}>
                <p className="muted">Connect your wallet to play</p>
                <button className="btn btn-primary" onClick={() => void connect()} style={{ marginTop: '12px' }}>
                  Connect Wallet
                </button>
              </div>
            ) : (
              <div className="row" style={{ marginTop: '24px' }}>
                <button className="btn btn-primary" onClick={() => setView('create')}>
                  Create Match
                </button>
                <button className="btn" onClick={() => setView('join')}>
                  Join with Code
                </button>
              </div>
            )}
          </div>
        );

      case 'create':
        return (
          <div className="lobby-content">
            <h1>Create Match</h1>
            <p className="muted">Select bet amount and share the code</p>

            <div className="bet-selector" style={{ marginTop: '24px' }}>
              <label className="muted">Bet Amount (KAS)</label>
              <div className="row" style={{ marginTop: '8px', flexWrap: 'wrap', gap: '8px' }}>
                {BET_AMOUNTS.map((amount) => (
                  <button
                    key={amount}
                    className={`btn ${betAmount === amount ? 'btn-primary' : ''}`}
                    onClick={() => setBetAmount(amount)}
                  >
                    {amount} KAS
                  </button>
                ))}
              </div>
            </div>

            {error && <p className="error" style={{ marginTop: '16px' }}>{error}</p>}

            <div className="row" style={{ marginTop: '24px' }}>
              <button
                className="btn btn-primary"
                onClick={handleCreateMatch}
                disabled={loading}
              >
                {loading ? 'Creating...' : 'Create Match'}
              </button>
              <button className="btn" onClick={() => setView('lobby')}>
                Cancel
              </button>
            </div>
          </div>
        );

      case 'join':
        return (
          <div className="lobby-content">
            <h1>Join Match</h1>
            <p className="muted">Enter the 6-character code</p>

            <div style={{ marginTop: '24px' }}>
              <input
                type="text"
                className="input-code"
                placeholder="ABC123"
                value={joinCode}
                onChange={(e) => setJoinCode(e.target.value.toUpperCase().slice(0, 6))}
                maxLength={6}
                style={{
                  fontSize: '24px',
                  textAlign: 'center',
                  letterSpacing: '8px',
                  padding: '12px 24px',
                  width: '200px',
                  textTransform: 'uppercase',
                }}
              />
            </div>

            {error && <p className="error" style={{ marginTop: '16px' }}>{error}</p>}

            <div className="row" style={{ marginTop: '24px' }}>
              <button
                className="btn btn-primary"
                onClick={handleJoinMatch}
                disabled={loading || joinCode.length !== 6}
              >
                {loading ? 'Joining...' : 'Join Match'}
              </button>
              <button className="btn" onClick={() => setView('lobby')}>
                Cancel
              </button>
            </div>
          </div>
        );

      case 'waiting':
        return (
          <div className="lobby-content">
            <h1>Waiting for Opponent</h1>
            <p className="muted">Share this code with your opponent</p>

            <div className="join-code" style={{
              marginTop: '24px',
              fontSize: '48px',
              fontWeight: 'bold',
              letterSpacing: '12px',
              color: 'var(--accent-primary)',
            }}>
              {match?.joinCode}
            </div>

            <p className="muted" style={{ marginTop: '8px', fontSize: '12px' }}>
              Code is case-insensitive
            </p>

            <button
              className="btn"
              onClick={() => void navigator.clipboard.writeText(match?.joinCode ?? '')}
              style={{ marginTop: '16px' }}
            >
              Copy Code
            </button>

            <div className="spinner" style={{ marginTop: '32px' }}>
              <div className="loading-dots">
                <span>Waiting</span>
                <span className="dot">.</span>
                <span className="dot">.</span>
                <span className="dot">.</span>
              </div>
            </div>

            <button className="btn" onClick={resetMatch} style={{ marginTop: '24px' }}>
              Cancel Match
            </button>
          </div>
        );

      case 'deposits':
        return (
          <div className="lobby-content">
            <h1>Deposit Required</h1>
            <p className="muted">Both players must deposit to start the race</p>

            <div className="deposit-status" style={{ marginTop: '24px' }}>
              <div className="deposit-card" style={{
                padding: '16px',
                background: 'rgba(255,255,255,0.05)',
                borderRadius: '8px',
                marginBottom: '12px',
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span>Your Deposit ({myPlayer})</span>
                  <span style={{
                    color: myDeposit?.depositTxid ? 'var(--accent-primary)' : 'var(--text-muted)',
                  }}>
                    {myDeposit?.depositTxid ? '✓ Deposited' : 'Pending'}
                  </span>
                </div>
                {myDeposit?.depositTxid && (
                  <TxLifecycleTimeline
                    txid={myDeposit.depositTxid}
                    status={(myDeposit.depositStatus as 'broadcasted' | 'accepted' | 'included' | 'confirmed') ?? 'broadcasted'}
                    timestamps={{ broadcasted: Date.now() }}
                    network={network}
                  />
                )}
              </div>

              <div className="deposit-card" style={{
                padding: '16px',
                background: 'rgba(255,255,255,0.05)',
                borderRadius: '8px',
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span>Opponent Deposit ({myPlayer === 'A' ? 'B' : 'A'})</span>
                  <span style={{
                    color: opponentDeposit?.depositTxid ? 'var(--accent-primary)' : 'var(--text-muted)',
                  }}>
                    {opponentDeposit?.depositTxid ? '✓ Deposited' : 'Waiting...'}
                  </span>
                </div>
                {opponentDeposit?.depositTxid && (
                  <TxLifecycleTimeline
                    txid={opponentDeposit.depositTxid}
                    status={(opponentDeposit.depositStatus as 'broadcasted' | 'accepted' | 'included' | 'confirmed') ?? 'broadcasted'}
                    timestamps={{ broadcasted: Date.now() }}
                    network={network}
                  />
                )}
              </div>
            </div>

            {!myDeposit?.depositTxid && (
              <>
                {error && <p className="error" style={{ marginTop: '16px' }}>{error}</p>}
                <button
                  className="btn btn-primary"
                  onClick={handleDeposit}
                  disabled={depositLoading}
                  style={{ marginTop: '24px', width: '100%' }}
                >
                  {depositLoading ? 'Processing...' : `Deposit ${match?.betAmount} KAS`}
                </button>
              </>
            )}

            <button className="btn" onClick={resetMatch} style={{ marginTop: '16px' }}>
              Cancel
            </button>
          </div>
        );

      case 'game':
        return (
          <div className="lobby-content">
            <h1>Race in Progress</h1>
            <p className="muted">Both deposits confirmed. Race is running...</p>

            <div style={{ marginTop: '24px' }}>
              <p className="muted">Navigate to game scene or check match status.</p>
            </div>

            <button className="btn" onClick={resetMatch} style={{ marginTop: '24px' }}>
              Back to Lobby
            </button>
          </div>
        );

      case 'finished': {
        const isWinner = match?.winner === myPlayer;
        const isDraw = match?.winner === 'draw';
        const winnerLabel = match?.winner === 'A' ? 'Player A' : match?.winner === 'B' ? 'Player B' : 'Draw';

        return (
          <div className="lobby-content">
            <h1>
              {isDraw ? 'Draw!' : isWinner ? 'You Win!' : 'You Lose'}
            </h1>
            <p className="muted">
              {isDraw
                ? 'Both players scored the same.'
                : `Winner: ${winnerLabel}`}
            </p>

            <div className="result-scores" style={{
              marginTop: '24px',
              display: 'flex',
              gap: '24px',
              justifyContent: 'center',
            }}>
              <div style={{ textAlign: 'center' }}>
                <div className="muted">Player A</div>
                <div style={{ fontSize: '32px', fontWeight: 'bold' }}>
                  {match?.playerAScore?.toLocaleString() ?? '-'}
                </div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div className="muted">Player B</div>
                <div style={{ fontSize: '32px', fontWeight: 'bold' }}>
                  {match?.playerBScore?.toLocaleString() ?? '-'}
                </div>
              </div>
            </div>

            {/* Settlement Transaction */}
            {match?.settleTxid && (
              <div style={{ marginTop: '24px' }}>
                <h3>Settlement Transaction</h3>
                <TxLifecycleTimeline
                  txid={match.settleTxid}
                  status={(match.settleStatus as 'broadcasted' | 'accepted' | 'included' | 'confirmed') ?? 'broadcasted'}
                  timestamps={{ broadcasted: Date.now() }}
                  network={network}
                />
              </div>
            )}

            {isDraw && (
              <p className="muted" style={{ marginTop: '16px', fontSize: '14px' }}>
                In a draw, deposits will be returned (feature pending).
              </p>
            )}

            <button className="btn btn-primary" onClick={resetMatch} style={{ marginTop: '24px' }}>
              Play Again
            </button>
          </div>
        );
      }
    }
  };

  const renderSidebar = () => {
    switch (view) {
      case 'lobby':
        return (
          <>
            <h2>Duel Rules</h2>
            <ul className="muted" style={{ fontSize: '14px', lineHeight: '1.8' }}>
              <li>Both players deposit the bet amount</li>
              <li>30-second race starts when deposits confirm</li>
              <li>Highest distance wins the pot</li>
              <li>Winner receives both deposits (minus fees)</li>
            </ul>
          </>
        );

      case 'create':
        return (
          <>
            <h2>Create Match</h2>
            <div className="match-info">
              <div className="stat-item">
                <span className="stat-label">Your Wallet</span>
                <span className="stat-value" style={{ fontSize: '12px' }}>
                  {address?.slice(0, 12)}...{address?.slice(-6)}
                </span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Bet Amount</span>
                <span className="stat-value">{betAmount} KAS</span>
              </div>
            </div>
          </>
        );

      case 'join':
        return (
          <>
            <h2>Join Match</h2>
            <p className="muted">Get the code from your opponent</p>
            <div className="match-info" style={{ marginTop: '16px' }}>
              <div className="stat-item">
                <span className="stat-label">Your Wallet</span>
                <span className="stat-value" style={{ fontSize: '12px' }}>
                  {address?.slice(0, 12)}...{address?.slice(-6)}
                </span>
              </div>
            </div>
          </>
        );

      case 'waiting':
        return (
          <>
            <h2>Match Details</h2>
            <div className="match-info">
              <div className="stat-item">
                <span className="stat-label">Bet Amount</span>
                <span className="stat-value">{match?.betAmount} KAS</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Status</span>
                <span className="stat-value">Waiting for opponent</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">You are</span>
                <span className="stat-value">Player A</span>
              </div>
            </div>
          </>
        );

      case 'deposits':
        return (
          <>
            <h2>Match #{match?.joinCode}</h2>
            <div className="match-info">
              <div className="stat-item">
                <span className="stat-label">Bet Amount</span>
                <span className="stat-value">{match?.betAmount} KAS</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Total Pot</span>
                <span className="stat-value">{(match?.betAmount ?? 0) * 2} KAS</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Status</span>
                <span className="stat-value">{match?.status}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Player A</span>
                <span className="stat-value" style={{ fontSize: '11px' }}>
                  {match?.playerA?.address?.slice(0, 10)}...
                </span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Player B</span>
                <span className="stat-value" style={{ fontSize: '11px' }}>
                  {match?.playerB?.address?.slice(0, 10)}...
                </span>
              </div>
            </div>
          </>
        );

      case 'game':
        return (
          <>
            <h2>Race</h2>
            <div className="match-info">
              <div className="stat-item">
                <span className="stat-label">Total Pot</span>
                <span className="stat-value">{(match?.betAmount ?? 0) * 2} KAS</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Status</span>
                <span className="stat-value">{match?.status}</span>
              </div>
            </div>
          </>
        );

      case 'finished':
        return (
          <>
            <h2>Match Complete</h2>
            <div className="match-info">
              <div className="stat-item">
                <span className="stat-label">Total Pot</span>
                <span className="stat-value">{(match?.betAmount ?? 0) * 2} KAS</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Winner</span>
                <span className="stat-value">
                  {match?.winner === 'draw' ? 'Draw' : `Player ${match?.winner}`}
                </span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Settlement</span>
                <span className="stat-value" style={{ fontSize: '12px' }}>
                  {match?.settleTxid ? match.settleTxid.slice(0, 12) + '...' : 'Pending'}
                </span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Settle Status</span>
                <span className="stat-value">{match?.settleStatus ?? 'pending'}</span>
              </div>
            </div>
          </>
        );
    }
  };

  return (
    <div className="layout">
      <main className="game">
        {renderMainContent()}
      </main>
      <aside className="panel">
        {renderSidebar()}
        <div style={{ marginTop: 'auto' }}>
          <Link className="btn" to="/">
            Back Home
          </Link>
        </div>
      </aside>
    </div>
  );
}
